from python:3.8


#APP Directory
WORKDIR /ip_tor_api

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

RUN apt-get -y update
RUN apt-get -y install iputils-ping

COPY . .

EXPOSE 4000

CMD ["python","app.py"]